repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.

  - repo: https://github.com/PyCQA/bandit
    rev: v1.7.9
    hooks:
      - id: bandit
        pass_filenames: 
        additional_dependencies: ["bandit[toml]"]
        args: ["-c", "pyproject.toml", "-r", "-ll", "-f", "screen"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Use local mypy installation so we can check imported libraries
  - repo: local
    hooks:
      - id: mypy
        name: MyPy Type-Checker
        entry: poetry run mypy
        types_or: [python, pyi]
        language: python
        pass_filenames: false
